<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Extraordinary.Services\Extraordinary.Services.csproj" />
	</ItemGroup>

	<Import Project="..\.paket\Paket.Restore.targets" />
</Project>