<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<ContentWithTargetPath Include="StaticFiles\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>StaticFiles\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>

	<Import Project="..\.paket\Paket.Restore.targets" />

	<ItemGroup>
	  <ProjectReference Include="..\Extraordinary.Shared\Extraordinary.Shared.csproj" />
	</ItemGroup>
</Project>